name: dumbdumb_flutter_app
description: My dumbdumb Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # State Management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  # Device Info
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  store_redirect: ^2.0.1

  # Data
  dio: ^5.4.0
  shared_preferences: ^2.0.5
  uuid: ^4.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.2.0

  # Firebase
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_messaging: ^14.2.1
  firebase_crashlytics: ^3.0.11
  firebase_remote_config: ^4.3.8

  # Push Notification
  flutter_local_notifications: ^16.3.0

  # UI / UX
  flutter_animate: ^4.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
