name: dumbdumb_flutter_app
description: My dumbdumb Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  provider: ^6.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Device Info
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  store_redirect: ^2.0.1

  # Data
  dio: ^4.0.0
  shared_preferences: ^2.0.5
  uuid: ^3.0.6

  # Firebase
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_messaging: ^14.2.1
  firebase_crashlytics: ^3.0.11
  firebase_remote_config: ^3.0.9

  # Push Notification
  flutter_local_notifications: ^13.0.0

  # UI / UX
  flutter_animate: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
